name: Automerge

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - reopened
  pull_request_target:
    types: [ labeled ]  # For forks & bots like Dependabot

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - name: Debug PR info
        run: |
          echo "PR author: ${{ github.event.pull_request.user.login }}"
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"

      - name: Auto-approve if opened by github-actions or dependabot
        if: |
          github.event.pull_request.user.login == 'github-actions[bot]' ||
          github.event.pull_request.user.login == 'dependabot[bot]' ||
          github.event.pull_request.user.login == 'viseshrp'
        uses: hmarr/auto-approve-action@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ github.event.pull_request.number }}

      - name: Confirm automerge is enabled
        run: gh pr view ${{ github.event.pull_request.number }} --json autoMergeRequest
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
